spring:

  #  datasource
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:23307/board
    username: root
    password: boardmaria
    #  data.sql  and  schema.sql
    initialization-mode: always

  #  mvc
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  #  http
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true